INSERT INTO tracked_entities (name, type, aliases, metadata) VALUES
('OpenAI', 'company', '["openai"]', '{"sector": "foundation_models"}'),
('Anthropic', 'company', '["anthropic"]', '{"sector": "foundation_models"}'),
('Google DeepMind', 'company', '["deepmind", "google ai"]', '{"sector": "foundation_models"}'),
('Meta AI', 'company', '["meta fair", "llama"]', '{"sector": "foundation_models"}'),
('Mistral AI', 'company', '["mistral"]', '{"sector": "foundation_models"}'),
('Cohere', 'company', '["cohere"]', '{"sector": "foundation_models"}'),
('Databricks', 'company', '["mosaic ml", "dbrx"]', '{"sector": "infra_platform"}'),
('Hugging Face', 'company', '["huggingface", "hf"]', '{"sector": "infra_platform"}'),
('NVIDIA', 'company', '["nvidia"]', '{"sector": "compute"}'),
('AMD', 'company', '["amd"]', '{"sector": "compute"}'),
('Groq', 'company', '["groq"]', '{"sector": "inference"}'),
('Together AI', 'company', '["together"]', '{"sector": "inference"}'),
('Fireworks AI', 'company', '["fireworks"]', '{"sector": "inference"}'),
('Anyscale', 'company', '["anyscale", "ray"]', '{"sector": "infra_platform"}'),
('LangChain', 'company', '["langchain", "langsmith"]', '{"sector": "tooling"}'),
('LlamaIndex', 'company', '["llamaindex"]', '{"sector": "tooling"}'),
('Weights & Biases', 'company', '["wandb"]', '{"sector": "mlops"}'),
('Scale AI', 'company', '["scale"]', '{"sector": "data"}'),
('Replit', 'company', '["replit"]', '{"sector": "ai_coding"}'),
('Cursor', 'company', '["cursor", "anysphere"]', '{"sector": "ai_coding"}');
